CREATE USER IF NOT EXISTS 'stephen'@'localhost' IDENTIFIED BY 'YES';

DROP DATABASE IF EXISTS GIFLIBDB;

CREATE DATABASE GIFLIBDB;
USE GIFLIBDB;
GRANT ALL PRIVILEGES ON GIFLIBDB.* to 'stephen'@'localhost';
FLUSH PRIVILEGES;

SET GLOBAL time_zone = '+5:00';